stages:
  - build

build_project:
  stage: build
  script:
    - xcodebuild clean -workspace TinggIOS.xcworkspace -scheme TinggIOS | xcpretty
    - xcodebuild test -workspace TinggIOS.xcworkspace -scheme TinggIOS -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=15' | xcpretty -s
  tags:
    - tinggios_0.1.0
