stages:
  - build
  - test
  
before_script:
 - echo "started by ${GITLAB_USER_NAME}"

build_project:
  stage: build
  script:
    - xcodebuild clean -workspace TinggIOS/TinggIOS.xcworkspace -scheme TinggIOS | xcpretty

  tags:
    - ios
  image: macos-13-xcode-14

test_project:
    stage: test
    script:
        - xcodebuild test -workspace TinggIOS/TinggIOS.xcworkspace -scheme TinggIOS -destination 'platform=iOS Simulator,name=iPhone 14' -enableCodeCoverage YES | xcpretty -s
        - xcresultparser -c -o xml /Users/darot/Library/Developer/Xcode/DerivedData/TinggIOS-barqglrxrsszsvcbkgkjuftpivba/Logs/Test/*.xcresult > coverage.xml
    allow_failure: true
    only:
        - merge_requests
        - feature/master
    tags:
        - ios




